"""Create pitch table

Revision ID: bcb167cb67ef
Revises: 1bb06b047280
Create Date: 2022-03-07 11:38:54.009444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb167cb67ef'
down_revision = '1bb06b047280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'body')
    # ### end Alembic commands ###
